# **NumPy**
**Numerical Python**

---


* Allow several mathematical operations.
*Faster operations compared to normal list and tuples.



In [38]:
import numpy as np

**List vs NumPy - Time Taken**

---



In [39]:
from time import process_time

Time taken by a list

In [40]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)


0.0


In [41]:
arr = np.array([i for i in range(10000)])

start_time = process_time()

arr += 5     # Adds 5 to all elememts of array.

end_time = process_time()

print(end_time - start_time)


0.0


**NumPy Arrays**

---



In [42]:
#List
list_1 = [1,2,3,4.5]
print(list_1)
type(list_1)


[1, 2, 3, 4.5]


list

In [43]:
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)  #  nd represents n dimensional arrays.

[1 2 3 4 5]


numpy.ndarray

In [44]:
# creating a one dimensional array.
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [45]:
a.shape

(4,)

In [46]:
import pandas as pd
# creating a two dimensional array.
b = np.array([(1,2,3),(4,5,6)])
print(b)
type(b)
b.ndim
b.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [47]:
# creating a three dimensional array.
c = np.array([(1,2,3),(3,4,5),(7,8,9)],dtype = float)
print(c)
c.shape
#c.ndim
#type(c)

[[1. 2. 3.]
 [3. 4. 5.]
 [7. 8. 9.]]


(3, 3)

**Initial PlaceHolders in NumPy arrays**

---



In [48]:
# create a numpy arrays of zeros.
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# creating a numpy array of ones.
y = np.ones((4,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# array of a particular value.
z = np.full((3,3),5)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
# create an identity matrix.
a = np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# create a numpy array with random values.
b = np.random.random((3,3))
print(b)

[[0.68086241 0.92053927 0.28614166]
 [0.69343556 0.0152104  0.35947136]
 [0.87178746 0.9975704  0.9319891 ]]


In [17]:
# creating a random values array within a specific range.
c = np.random.randint(10,100,(3,3))
print(c)

[[78 97 96]
 [67 47 41]
 [11 92 54]]


In [18]:
# creating an array of evenly spaced values -- specifying the number of values required.
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# creating array of evenly spaced values --- specifying the step.
e = np.arange(10,30,4)
print(e)

[10 14 18 22 26]


In [20]:
# converting a list to a numpy array.
list2 = [10,20,30,4,40]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30  4 40]


numpy.ndarray

In [21]:
# converting a tuple to an array.
tuple = {1,2,3,4,5}
np_array = np.asarray(tuple)
print(np_array)

{1, 2, 3, 4, 5}


**Analysing NumPy array**

---



In [22]:
c = np.random.randint(10,90,(3,3))
print(c)

[[25 20 64]
 [11 86 81]
 [33 78 64]]


In [23]:
# array dimension
print(c.shape)

(3, 3)


In [24]:
# number of dimensions
print(c.ndim)

2


In [25]:
# number of elements in an array.
print(c.size)

9


In [26]:
# checking datatype of values in the array.
print(c.dtype)

int32


**Mathematical Operations on a NumPy array.**

---



In [27]:
list1 = [1,2,3,4,5,]
list2 = [6,7,8,9,10]
print(list1+list2)             #Concatenated list.

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 3 0]
 [0 4 3]
 [7 3 4]]
[[11 16 15]
 [10 12 14]
 [15 12 14]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[12 19 15]
 [10 16 17]
 [22 15 18]]
[[-10 -13 -15]
 [-10  -8 -11]
 [ -8  -9 -10]]
[[ 11  48   0]
 [  0  48  42]
 [105  36  56]]
[[0.09090909 0.1875     0.        ]
 [0.         0.33333333 0.21428571]
 [0.46666667 0.25       0.28571429]]


In [30]:
a = np.random.randint(10,20,(3,3))
b = np.random.randint(20,30,(3,3))
print(a,b)

[[12 13 18]
 [15 18 11]
 [15 14 15]] [[21 20 26]
 [25 28 23]
 [29 25 24]]


In [31]:
print(np.add(a,b))
print(np.multiply(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[[33 33 44]
 [40 46 34]
 [44 39 39]]
[[252 260 468]
 [375 504 253]
 [435 350 360]]
[[ -9  -7  -8]
 [-10 -10 -12]
 [-14 -11  -9]]
[[0.57142857 0.65       0.69230769]
 [0.6        0.64285714 0.47826087]
 [0.51724138 0.56       0.625     ]]


**Array Manipulation**

---



In [32]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 9 8]
 [4 8 0]]
(2, 3)


In [33]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 4]
 [9 8]
 [8 0]]
(3, 2)


In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 2 2]
 [3 0 6]]
(2, 3)


In [35]:
 trans2 = array.T
 print(trans2)
 print(trans2.shape)

[[4 3]
 [2 0]
 [2 6]]
(3, 2)


In [36]:
# reshaping an array.
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 5 5]
 [7 5 4]]
(2, 3)


In [37]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 5]
 [5 7]
 [5 4]]
(3, 2)
